# Generated by Django 2.0 on 2020-04-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('number', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pti', models.CharField(max_length=500)),
                ('pde', models.TextField()),
                ('sen', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='us',
            fields=[
                ('Email', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='pus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.us'),
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.us'),
        ),
    ]
